### ISSUE TITLE
Missing special characters in product names

### ISSUE THREAD

**Issue by mybinaryromance** [mollie/Magento#194]
Mollie library has an issue when passing special characters ('umlaut' like ä, ü, ö) in product names. These characters are properly encoded when in customer names ('Süleyman' => => "givenName":"S\u00fcleyman"), but not in product names ('Känguru' => 'Knguru'). The missing encoding occurs in mollie.log and in Mollie Customer Backend.

**Comment by Frank-Magmodules** [comment]
Hi @mybinaryromance,

Good idea! We are happy to share that we've just released the new [5.6.3](https://github.com/mollie/Magento/releases/tag/v5.6.3) version with an improvement for this issue. Thank you for sharing this idea. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by mybinaryromance** [comment]
I updated to 5.6.3, but the issue still persists. The text in the screenshots is supposed to be 'Knguru' => 'Känguru' and 'fr' => 'für'.
![Screenshot from 2021-01-27 15-46-18](https://user-images.githubusercontent.com/8794344/106008112-481bdf80-60b7-11eb-8e1f-3de44d7724ec.png)
![Screenshot from 2021-01-27 15-46-48](https://user-images.githubusercontent.com/8794344/106008174-54a03800-60b7-11eb-9df3-1adbeaa040ad.png)

**Comment by mybinaryromance** [comment]
Sorry guys, the issue still persists with release 5.6.6 - see screenshot attached, 'Sukartoffel' is supposed to read 'Süßkartoffel' ;)
![Screenshot from 2021-06-29 14-30-41](https://user-images.githubusercontent.com/8794344/123797828-e3bfaf00-d8e6-11eb-824c-9280d88bbd13.png)
